services:
  - type: web
    name: weather-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weather_chat:app
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false 